name: 'Build GitHub Pages'
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
         lfs: true
    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install bundler
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
    - name: Install missing gems
      run: bundle install
      working-directory: slides
    - name: Build pages
      run: make
      working-directory: slides
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
