name: 'Build image'
on:
  push:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
         lfs: true
    - name: Install make
      run: |
        sudo apt-get update
        sudo apt-get install make
    - name: Install Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Install bundler
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
    - name: Install missing gems
      run: bundle install
      working-directory: slides
    - name: Build pages
      run: make
      working-directory: slides
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: hermitcore
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build httpd
      run: |
        cargo build -Zbuild-std=core,alloc,std,panic_abort -Zbuild-std-features=compiler-builtins-mem --target x86_64-unknown-hermit --release
        cd loader
        cargo xtask build --arch x86_64 --release
    - name: Create dockerfile
      run: |
        cat << END > Dockerfile
        FROM scratch
        COPY loader/target/x86_64/release/rusty-loader hermit/rusty-loader
        COPY target/x86_64-unknown-hermit/release/httpd hermit/httpd
        CMD ["/hermit/httpd"]
        END
    - name: Build and push container
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/hermitcore/tutorial:latest